### ISSUE TITLE
ToDo - Frontend - #2

### ISSUE THREAD

**Issue by NathanFRibeiro** [NathanFRibeiro/gympoint#4]
### API
- [x] Connect api

### Pages

- [x] Student
- [x] Plan
- [x] Enrollment
- [x] Help Order

### Auth
- [x] Persist with redux

### others

- [x] Fix all lint warnings and erros
- [x] Remove console.log 
- [x] Insert info when items == 0
